on: push
name: Clippy check

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm/lib/

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy && clang --version
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Clippy default
