name: Rust

on: push

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-11/lib/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install apt-get
      run: sudo apt-get install -y clang
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests (with address sanitizer)
      run: LSAN_OPTIONS=suppressions=san.supp RUSTFLAGS="-Zsanitizer=address" cargo +nightly test --verbose
